apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-app
  namespace: argocd
  labels:
    clusterid: cluster-01
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/app-of-apps.git
    targetRevision: HEAD
    path: app-of-apps/actions/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
